### ISSUE TITLE
A GAN review for Computer Vision in 2021 Published at ACM Computing Surveys

### ISSUE THREAD

**Issue by sheqi** [52CV/2021-CV-Surveys#2]
We have a A GAN review for Computer Vision in 2021 Published at ACM Computing Surveys，which can be added in this repo.

"Generative Adversarial Networks in Computer Vision: A Survey and Taxonomy"
Zhengwei Wang, Qi She, Tomas Ward

ArXiv: https://arxiv.org/abs/1906.01529
Published Version: https://dl.acm.org/doi/fullHtml/10.1145/3439723
Code: https://github.com/sheqi/GAN_Review

**Comment by 52CV** [comment]
收到，thanks
